#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_PROTOCOL_SCHEMA_VERSION "axon.ihm.v1"
#define APP_FIRMWARE_VERSION "ihm-devkit-v1-comm-0.1.0"

#define APP_DEVICE_ID_MAX_LEN 48
#define APP_TOPIC_PREFIX_MAX_LEN 64
#define APP_URI_MAX_LEN 192
#define APP_USERNAME_MAX_LEN 64
#define APP_PASSWORD_MAX_LEN 64
#define APP_SSID_MAX_LEN 32
#define APP_WIFI_PASSWORD_MAX_LEN 64
#define APP_CODE_MAX_LEN 48
#define APP_MESSAGE_MAX_LEN 160
#define APP_COMMAND_ID_MAX_LEN 48
#define APP_SCHEDULE_ID_MAX_LEN 48
#define APP_SCHEDULE_MAX_COUNT 16
#define APP_REVISION_MAX_LEN 48
#define APP_TIMEZONE_NAME_MAX_LEN 64
#define APP_TIMESTAMP_MAX_LEN 32
#define APP_ONE_SHOT_DATE_LEN 10

#define APP_WIFI_STA_SSID_DEFAULT ""
#define APP_WIFI_STA_PASSWORD_DEFAULT ""
#define APP_WIFI_MAXIMUM_RETRY 5
#define APP_WIFI_AP_SSID_PREFIX "AXON-IHM-"
#define APP_WIFI_AP_PASSWORD_DEFAULT ""
#define APP_WIFI_AP_MAX_CONNECTIONS 4
#define APP_WIFI_AP_CHANNEL 1

#define APP_MQTT_ENABLED_DEFAULT 1
#define APP_MQTT_USE_TLS_DEFAULT 1
#define APP_MQTT_URI_DEFAULT "mqtts://b11f6b00.ala.eu-central-1.emqxsl.com"
#define APP_MQTT_PORT_DEFAULT 8883
#define APP_MQTT_USERNAME_DEFAULT "ihm-devkit32-v1"
#define APP_MQTT_PASSWORD_DEFAULT "ihm_devkit_teste"
#define APP_MQTT_KEEPALIVE_SEC_DEFAULT 60
#define APP_TOPIC_PREFIX_DEFAULT "axon/ihm"

#define APP_NVS_NAMESPACE_COMM "commcfg"
#define APP_NVS_NAMESPACE_SCHEDULES "schedcfg"
#define APP_NVS_KEY_SCHEDULE_STORE "store"

#define APP_STATUS_PUBLISH_INTERVAL_MS 10000
#define APP_MQTT_TASK_STACK_SIZE 4096
#define APP_MQTT_TASK_PRIORITY 4
#define APP_LOCAL_SERVER_PORT_DEFAULT 8080
#define APP_LOCAL_SERVER_CORS_ENABLED 1
#define APP_HTTP_BODY_BUFFER_SIZE 2048
#define APP_HTTP_RESTART_DELAY_MS 1200
#define APP_SCHEDULE_TASK_STACK_SIZE 4096
#define APP_SCHEDULE_TASK_PRIORITY 3
#define APP_SCHEDULE_POLL_INTERVAL_MS 1000

#define APP_SCHEDULE_TZ_OFFSET_MIN_DEFAULT (-180)
#define APP_SNTP_SERVER_PRIMARY "pool.ntp.org"
#define APP_SNTP_SERVER_SECONDARY "time.google.com"
#define APP_TIME_VALID_UNIX_THRESHOLD 1704067200

#endif
