#include "comm_storage.h"
#include <stdio.h>
#include <string.h>
#include "esp_log.h"
#include "esp_mac.h"
#include "nvs.h"
#include "log_tags.h"
static void copy_string(char *dst, size_t len, const char *src){ if(!dst||len==0)return; dst[0]='\0'; if(src)strncpy(dst,src,len-1); }
static void fill_default_device_id(char *device_id, size_t len){ uint8_t mac[6]={0}; esp_read_mac(mac, ESP_MAC_WIFI_STA); snprintf(device_id,len,"ihm32-%02X%02X%02X",mac[3],mac[4],mac[5]); }
static void nvs_get_string_or_keep(nvs_handle_t h,const char *key,char *value,size_t len){ size_t required=len; esp_err_t err=nvs_get_str(h,key,value,&required); if(err!=ESP_OK&&err!=ESP_ERR_NVS_NOT_FOUND) ESP_LOGW(LOG_TAG_COMM_STORAGE,"Falha ao ler %s: %s",key,esp_err_to_name(err)); }
esp_err_t comm_storage_load_wifi_config(app_wifi_config_t *config){ nvs_handle_t h=0; uint8_t enabled=APP_WIFI_STA_SSID_DEFAULT[0]!='\0'; if(!config)return ESP_ERR_INVALID_ARG; memset(config,0,sizeof(*config)); config->sta_enabled=enabled!=0; config->max_retry=APP_WIFI_MAXIMUM_RETRY; copy_string(config->sta_ssid,sizeof(config->sta_ssid),APP_WIFI_STA_SSID_DEFAULT); copy_string(config->sta_password,sizeof(config->sta_password),APP_WIFI_STA_PASSWORD_DEFAULT); if(nvs_open(APP_NVS_NAMESPACE_COMM,NVS_READONLY,&h)!=ESP_OK)return ESP_OK; (void)nvs_get_u8(h,"wifi_en",&enabled); config->sta_enabled=enabled!=0; nvs_get_string_or_keep(h,"wifi_ssid",config->sta_ssid,sizeof(config->sta_ssid)); nvs_get_string_or_keep(h,"wifi_pass",config->sta_password,sizeof(config->sta_password)); nvs_close(h); return ESP_OK; }
esp_err_t comm_storage_load_mqtt_config(app_mqtt_config_t *config){ nvs_handle_t h=0; uint8_t enabled=APP_MQTT_ENABLED_DEFAULT; uint8_t tls=APP_MQTT_USE_TLS_DEFAULT; uint16_t port=APP_MQTT_PORT_DEFAULT; if(!config)return ESP_ERR_INVALID_ARG; memset(config,0,sizeof(*config)); config->enabled=APP_MQTT_ENABLED_DEFAULT!=0; config->use_tls=APP_MQTT_USE_TLS_DEFAULT!=0; config->port=APP_MQTT_PORT_DEFAULT; config->keepalive_sec=APP_MQTT_KEEPALIVE_SEC_DEFAULT; copy_string(config->broker_uri,sizeof(config->broker_uri),APP_MQTT_URI_DEFAULT); copy_string(config->username,sizeof(config->username),APP_MQTT_USERNAME_DEFAULT); copy_string(config->password,sizeof(config->password),APP_MQTT_PASSWORD_DEFAULT); copy_string(config->topic_prefix,sizeof(config->topic_prefix),APP_TOPIC_PREFIX_DEFAULT); fill_default_device_id(config->device_id,sizeof(config->device_id)); if(nvs_open(APP_NVS_NAMESPACE_COMM,NVS_READONLY,&h)!=ESP_OK)return ESP_OK; (void)nvs_get_u8(h,"mqtt_en",&enabled); (void)nvs_get_u8(h,"mqtt_tls",&tls); (void)nvs_get_u16(h,"mqtt_port",&port); config->enabled=enabled!=0; config->use_tls=tls!=0; config->port=port; nvs_get_string_or_keep(h,"mqtt_uri",config->broker_uri,sizeof(config->broker_uri)); nvs_get_string_or_keep(h,"mqtt_user",config->username,sizeof(config->username)); nvs_get_string_or_keep(h,"mqtt_pass",config->password,sizeof(config->password)); nvs_get_string_or_keep(h,"topic",config->topic_prefix,sizeof(config->topic_prefix)); nvs_get_string_or_keep(h,"device_id",config->device_id,sizeof(config->device_id)); nvs_close(h); if(config->topic_prefix[0]=='\0')copy_string(config->topic_prefix,sizeof(config->topic_prefix),APP_TOPIC_PREFIX_DEFAULT); if(config->device_id[0]=='\0')fill_default_device_id(config->device_id,sizeof(config->device_id)); return ESP_OK; }
